# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Autime' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Autime
  pod 'SwiftLint'

  target 'AutimeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AutimeUITests' do
    # Pods for testing
  end

end
